In [ ]:
#1)Write a Python program using the map() function to calculate the square of each element in the following list:

numbers = [2, 4, 6, 8, 10]
squared_numbers = list(map(lambda x: x**2,numbers))
print(squared_numbers)

[4, 16, 36, 64, 100]


In [ ]:
#2)Write a Python program using the map() function to convert the following list of strings into integers:

num_string = ["10", "20", "30", "40", "50"]
int_list = list(map(int,num_string))

print(int_list)

[10, 20, 30, 40, 50]


In [ ]:
#3)Write a Python program using the filter() function to extract all even numbers from the following list:

numbers = [11, 24, 35, 42, 57, 68, 73, 80]
even_nos = list(filter(lambda x: x%2==0,numbers))

print(even_nos)

[24, 42, 68, 80]


In [ ]:
#4) Write a Python program using the filter() function to extract all numbers greater than 50 from the following list:

numbers = [25, 65, 45, 80, 35, 95, 50]
result = list(filter(lambda x: x>50,numbers))

print(result)

[65, 80, 95]


In [ ]:
#5) Write a Python program using the reduce() function to calculate the sum of all elements in the following list:

from functools import reduce
a = [10, 20, 30, 40, 50]
sum = reduce(lambda x,y:x+y,a)

print(sum)

150


In [ ]:
 #6) Create the following 2-D NumPy array and write the slicing statement to extract the first two rows:
 #7)Using the same 2-D NumPy array given in Question 6, write the slicing statement to extract the last two columns.

 import numpy as np

In [ ]:
  arr = np.array([
                [10,20,30,40],
                [50,60,70,80],
                [90,100,110,120],
                [130,140,150,160]
  ])
  print(arr)
  print(arr[0:2,:])
  print(arr[:,2:])
  print(arr[1:3,2:])

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [130 140 150 160]]
[[10 20 30 40]
 [50 60 70 80]]
[[ 30  40]
 [ 70  80]
 [110 120]
 [150 160]]
[[ 70  80]
 [110 120]]


In [ ]:
#9.Create a 3-D NumPy array with shape (2, 3, 4) containing the numbers from 1 to 24. Write NumPy slicing statements to extract:

arr = np.arange(1,25).reshape(2,3,4)
print("Original array:",arr)

first_block = arr[0,:,:]
print(first_block)

print(arr[1, 0:2,:])

print(arr[:,:,2:])



Original array: [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]]
[[[ 3  4]
  [ 7  8]
  [11 12]]

 [[15 16]
  [19 20]
  [23 24]]]


In [ ]:
#10)Create the following 3-D NumPy array and write a slicing statement to extract all elements from the second dimension:
arr = np.array([[[1, 2, 3],
[4, 5, 6]],

[[7, 8, 9],
[10, 11, 12]]])
print(arr)
print(arr[1,:,:])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[ 7  8  9]
 [10 11 12]]


In [2]:
#11)Create a Pandas DataFrame using the following dictionary and display the DataFrame:

import pandas as pd

data = {
"Name": ["Rahul", "Amit", "Priya", "Sneha"],
"Age": [20, 21, 19, 22],
"Marks": [85, 78, 92, 88]
}

df = pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Rahul   20     85
1   Amit   21     78
2  Priya   19     92
3  Sneha   22     88


In [5]:
#12)Create a Pandas DataFrame containing the following information for at least five students:

import pandas as pd

data = {
    "Name": ["Sudhakar","Teja","Sandeep","Seshu","Geet mohan"],
    "Rollno":[45,50,52,60,71],
    "Department":["CSE","Mechanical","IT","Metallurgy","CSE"],
    "CGPA":[9,9,9.3,9.1,9.4]
}

df = pd.DataFrame(data)
print(df)


         Name  Rollno  Department  CGPA
0    Sudhakar      45         CSE   9.0
1        Teja      50  Mechanical   9.0
2     Sandeep      52          IT   9.3
3       Seshu      60  Metallurgy   9.1
4  Geet mohan      71         CSE   9.4


In [6]:
#13) Create a Pandas DataFrame from the following list of dictionaries and display the DataFrame:

import pandas as pd

data = [
{"Name": "Virat", "Runs": 12000, "Team": "India"},
{"Name": "Rohit", "Runs": 10000, "Team": "India"},
{"Name": "Gill", "Runs": 5000, "Team": "India"},
{"Name": "Dhoni", "Runs": 11000, "Team": "India"}
]

df = pd.DataFrame(data)
print(df)


    Name   Runs   Team
0  Virat  12000  India
1  Rohit  10000  India
2   Gill   5000  India
3  Dhoni  11000  India


In [11]:
#14) Create a Pandas DataFrame containing information about five employees with the following columns:

import pandas as pd

data = {
    "Employee_ID":[245,356,456,556,725],
    "Name": ["Sudhakar","Teja","Sandeep","Seshu","Geetmohan"],
    "Salary":[40000,50000,52000,60000,71000],
    "Department":["IT","Mechanical","IT","Metallurgy","IT"],

}

df = pd.DataFrame(data)
print(df,end="\n")
print(df[0:3],end="\n")
print(df[3:])
data.keys()

   Employee_ID       Name  Salary  Department
0          245   Sudhakar   40000          IT
1          356       Teja   50000  Mechanical
2          456    Sandeep   52000          IT
3          556      Seshu   60000  Metallurgy
4          725  Geetmohan   71000          IT
   Employee_ID      Name  Salary  Department
0          245  Sudhakar   40000          IT
1          356      Teja   50000  Mechanical
2          456   Sandeep   52000          IT
   Employee_ID       Name  Salary  Department
3          556      Seshu   60000  Metallurgy
4          725  Geetmohan   71000          IT


dict_keys(['Employee_ID', 'Name', 'Salary', 'Department'])

In [14]:
#15) Create a Pandas DataFrame containing the names of five students and their marks in three subjects: Python, Mathematics and Computer Science.

import pandas as pd

data = {
    "Name":["Rahul","Sudhakar","Sandeep","Teja","Seshu"],
    "Python":[85,90,94,92,84],
    "Mathematics":[87,92,94,91,90],
    "Computer Science":[85,86,88,93,80]
}

df = pd.DataFrame(data)
df["Total"] = df["Python"] + df["Mathematics"] + df["Computer Science"]

print(df)



       Name  Python  Mathematics  Computer Science  Total
0     Rahul      85           87                85    257
1  Sudhakar      90           92                86    268
2   Sandeep      94           94                88    276
3      Teja      92           91                93    276
4     Seshu      84           90                80    254
